name: Rust CI and Workspace Publish

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]    # triggers publish
  pull_request:
    branches: [ main, refacto ]

permissions:
  contents: read
  id-token: write  # required for trusted publishing

jobs:
  # ─────────────────────────────
  # CI: check, clippy, fmt, test
  # ─────────────────────────────
  ci:
    name: Static Analysis + Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: cargo check
        run: cargo check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: cargo test
        run: cargo test

  # ─────────────────────────────
  # Publish all workspace crates
  # ─────────────────────────────
  publish:
    name: Publish all crates to crates.io
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: crates-io
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Publish all workspace crates
        run: |
          echo "Searching for publishable crates..."
          for crate in db-moshi-core db-moshi-cli db-moshi-server db-moshi-backend db-mimi-pyo3; do
            echo "Attempting to publish: $crate"
            (
              cd "$crate"
              # dry-run to check if it should be published
              if cargo publish --locked --dry-run > /dev/null 2>&1; then
                echo "Publishing $crate..."
                cargo publish --locked --no-verify
              else
                echo "Skipping $crate (likely already published or not publishable)"
              fi
            )
          done
